/*
 * Please see the included README.md file for license terms and conditions.
 */


// This file is a suggested starting place for your code.
// It is completely optional and not required.
// Note the reference that includes it in the index.html file.


/*jslint browser:true, devel:true, white:true, vars:true */
/*global $:false, intel:false app:false, dev:false, cordova:false */


// For improved debugging and maintenance of your app, it is highly
// recommended that you separate your JavaScript from your HTML files.
// Use the addEventListener() method to associate events with DOM elements.

// For example:

// var el ;
// el = document.getElementById("id_myButton") ;
// el.addEventListener("click", myEventHandler, false) ;



// The function below is an example of the best way to "start" your app.
// This example is calling the standard Cordova "hide splashscreen" function.
// You can add other code to it or add additional functions that are triggered
// by the same event or other events.

function onAppReady() {
    if( navigator.splashscreen && navigator.splashscreen.hide ) {   // Cordova API detected
        navigator.splashscreen.hide() ;
    }
}
document.addEventListener("app.Ready", onAppReady, false) ;
// document.addEventListener("deviceready", onAppReady, false) ;
// document.addEventListener("onload", onAppReady, false) ;

// The app.Ready event shown above is generated by the init-dev.js file; it
// unifies a variety of common "ready" events. See the init-dev.js file for
// more details. You can use a different event to start your app, instead of
// this event. A few examples are shown in the sample code above. If you are
// using Cordova plugins you need to either use this app.Ready event or the
// standard Crordova deviceready event. Others will either not work or will
// work poorly.

// NOTE: change "dev.LOG" in "init-dev.js" to "true" to enable some console.log
// messages that can help you debug Cordova app initialization issues.

$(document).ready(function() {
    var id = localStorage.id;
    var url = "http://najd.ogail.net/app/info.php?id="+id;
    $.getJSON(url, function(result) {
        console.log(result);
        $.each(result, function(i, field) {
            var name = field.name;
            var id_num = field.id_num;
            var specialty = field.specialty;
            var phone = field.phone;
            $("#t_name").append(name);
            $("#t_id_num").append(id_num);
            $("#t_specialty").append(specialty);
            $("#t_phone").append(phone);
        });
    });
});
$(document).ready(function() {
    var id = localStorage.id;
    var url = "http://najd.ogail.net/app/view.php?id="+id;
    $.getJSON(url, function(result) {
        console.log(result);
        $.each(result, function(i, field) {
            var abs_t = field.abs_t;
            var abs_f = field.abs_f;
            var late_m = field.late_m;
            var late_c = field.late_c;
            var late_f = field.late_f;
            var vac = field.vac;
            $("#abs_t .abs_t").append(abs_t);
            $("#abs_f .abs_f").append(abs_f);
            $("#late_m .late_m").append(late_m);
            $("#late_c .late_c").append(late_c);
            $("#late_f .late_f").append(late_f);
            $("#vac .vac").append(vac);
        });
    });
});


